# Generated by Django 5.2.6 on 2025-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='Home', max_length=20)),
            ],
        ),
    ]
